import {
  AppstoreOutlined,
  BarChartOutlined,
  CarOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DownloadOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  HomeOutlined,
  InboxOutlined,
  NotificationOutlined,
  SafetyCertificateOutlined,
  SwapOutlined,
  TeamOutlined,
  UploadOutlined,
  UserOutlined,
} from '@ant-design/icons';

export const navigationItems = [
  { key: '/', label: 'Dashboard cá nhân', icon: DashboardOutlined, permission: 'dashboard.view' },
  { key: '/users', label: 'Tài khoản', icon: UserOutlined, permission: 'users.view' },
  { key: '/employees', label: 'Nhân sự', icon: TeamOutlined, permission: 'employees.view' },
  { key: '/products', label: 'Sản phẩm', icon: InboxOutlined, permission: 'products.view' },
  {
    key: '/warehouses',
    label: 'Kho bãi',
    icon: HomeOutlined,
    permissionAny: [
      'warehouses.view',
      'locations.view',
    ],
  },
  {
    key: '/import-receipts',
    label: 'Nhập kho',
    icon: DownloadOutlined,
    permission: 'import_receipts.view',
  },
  {
    key: '/export-receipts',
    label: 'Xuất kho',
    icon: UploadOutlined,
    permission: 'export_receipts.view',
  },
  {
    key: '/stock-transfers',
    label: 'Điều chuyển kho',
    icon: SwapOutlined,
    permission: 'stock_transfers.view',
  },
  {
    key: '/shipments',
    label: 'Vận chuyển',
    icon: CarOutlined,
    permission: 'shipments.view',
  },
  {
    key: '/invoices',
    label: 'Hóa đơn',
    icon: FileTextOutlined,
    permission: 'invoices.view',
  },
  {
    key: '/notifications',
    label: 'Công việc & thông báo',
    icon: NotificationOutlined,
    permissionAny: [
      'tasks.view',
      'notifications.view',
    ],
  },
  {
    key: '/reports',
    label: 'Báo cáo',
    icon: BarChartOutlined,
    permission: 'reports.view',
  },
  { key: '/inventory', label: 'Tồn kho', icon: DatabaseOutlined, permission: 'inventory.view' },
  { key: '/stocktakes', label: 'Kiểm kê kho', icon: FileSearchOutlined, permission: 'inventory.view' },
  {
    key: '/catalogs',
    label: 'Danh mục nền',
    icon: AppstoreOutlined,
    permissionAny: [
      'categories.view',
      'suppliers.view',
      'customers.view',
      'bank_accounts.view',
    ],
  },
  { key: '/delegations', label: 'Ủy quyền quyền hạn', icon: SwapOutlined, permission: 'delegations.manage' },
  { key: '/audit-logs', label: 'Audit log', icon: FileSearchOutlined, permission: 'audit_logs.view' },
  { key: '/roles', label: 'Vai trò và quyền', icon: SafetyCertificateOutlined, permission: 'roles.view' },
  { key: '/profile', label: 'Hồ sơ cá nhân', icon: UserOutlined, permission: null },
];
