import { formatCurrency, formatDateTime } from '../utils/format';

export const resourceConfig = {
  users: {
    title: 'Tai khoan nguoi dung',
    subtitle: 'Quan ly dang nhap, thong tin lien he va vai tro.',
    endpoint: '/users',
    permission: 'users.manage',
    columns: [
      { title: 'Username', dataIndex: 'username' },
      { title: 'Ho ten', dataIndex: 'full_name' },
      { title: 'Email', dataIndex: 'email' },
      { title: 'Vai tro', dataIndex: 'role' },
      { title: 'Trang thai', dataIndex: 'status', type: 'status' },
    ],
    fields: [
      { name: 'username', label: 'Username', required: true },
      { name: 'password', label: 'Mat khau', type: 'password' },
      { name: 'full_name', label: 'Ho ten', required: true },
      { name: 'email', label: 'Email', required: true },
      { name: 'phone', label: 'So dien thoai' },
      { name: 'role_id', label: 'Vai tro', type: 'select', required: true, options: { endpoint: '/roles', labelField: 'role_name', valueField: 'id' } },
      { name: 'status', label: 'Trang thai', type: 'select', options: { static: [{ label: 'Active', value: 'active' }, { label: 'Inactive', value: 'inactive' }] } },
    ],
  },
  employees: {
    title: 'Nhan su',
    subtitle: 'Ho so nhan vien va lien ket voi tai khoan.',
    endpoint: '/employees',
    permission: 'employees.view',
    columns: [
      { title: 'Ma NV', dataIndex: 'employee_code' },
      { title: 'Ho ten', dataIndex: 'full_name' },
      { title: 'Phong ban', dataIndex: 'department' },
      { title: 'Chuc vu', dataIndex: 'position' },
      { title: 'Role', dataIndex: 'role' },
      { title: 'Trang thai', dataIndex: 'status', type: 'status' },
    ],
    fields: [
      { name: 'employee_code', label: 'Ma nhan vien', required: true },
      { name: 'user_id', label: 'Tai khoan lien ket', type: 'select', options: { endpoint: '/directory/users', labelField: 'full_name', valueField: 'id' } },
      { name: 'full_name', label: 'Ho ten', required: true },
      { name: 'department', label: 'Phong ban' },
      { name: 'position', label: 'Chuc vu' },
      { name: 'phone', label: 'So dien thoai' },
      { name: 'email', label: 'Email' },
      { name: 'responsibility', label: 'Trach nhiem', type: 'textarea' },
      { name: 'status', label: 'Trang thai', type: 'select', options: { static: [{ label: 'Active', value: 'active' }, { label: 'Inactive', value: 'inactive' }] } },
    ],
  },
  categories: {
    title: 'Nhom hang',
    subtitle: 'Danh muc nhom san pham de thong ke va bao cao.',
    endpoint: '/categories',
    permission: 'categories.view',
    columns: [
      { title: 'Ten nhom', dataIndex: 'category_name' },
      { title: 'Mo ta', dataIndex: 'description' },
    ],
    fields: [
      { name: 'category_name', label: 'Ten nhom', required: true },
      { name: 'description', label: 'Mo ta', type: 'textarea' },
    ],
  },
  suppliers: {
    title: 'Nha cung cap',
    subtitle: 'Thong tin doi tac dau vao.',
    endpoint: '/suppliers',
    permission: 'suppliers.view',
    columns: [
      { title: 'Ma NCC', dataIndex: 'supplier_code' },
      { title: 'Ten nha cung cap', dataIndex: 'supplier_name' },
      { title: 'Email', dataIndex: 'email' },
      { title: 'Dien thoai', dataIndex: 'phone' },
      { title: 'Trang thai', dataIndex: 'status', type: 'status' },
    ],
    fields: [
      { name: 'supplier_code', label: 'Ma nha cung cap', required: true },
      { name: 'supplier_name', label: 'Ten nha cung cap', required: true },
      { name: 'email', label: 'Email' },
      { name: 'phone', label: 'So dien thoai' },
      { name: 'address', label: 'Dia chi', type: 'textarea' },
      { name: 'status', label: 'Trang thai', type: 'select', options: { static: [{ label: 'Active', value: 'active' }, { label: 'Inactive', value: 'inactive' }] } },
    ],
  },
  customers: {
    title: 'Khach hang',
    subtitle: 'Thong tin ben nhan hang va xuat hoa don.',
    endpoint: '/customers',
    permission: 'customers.view',
    columns: [
      { title: 'Ma KH', dataIndex: 'customer_code' },
      { title: 'Ten khach hang', dataIndex: 'customer_name' },
      { title: 'Email', dataIndex: 'email' },
      { title: 'Dien thoai', dataIndex: 'phone' },
      { title: 'Trang thai', dataIndex: 'status', type: 'status' },
    ],
    fields: [
      { name: 'customer_code', label: 'Ma khach hang', required: true },
      { name: 'customer_name', label: 'Ten khach hang', required: true },
      { name: 'email', label: 'Email' },
      { name: 'phone', label: 'So dien thoai' },
      { name: 'address', label: 'Dia chi', type: 'textarea' },
      { name: 'status', label: 'Trang thai', type: 'select', options: { static: [{ label: 'Active', value: 'active' }, { label: 'Inactive', value: 'inactive' }] } },
    ],
  },
  warehouses: {
    title: 'Kho bai',
    subtitle: 'Danh sach kho va nguoi phu trach.',
    endpoint: '/warehouses',
    permission: 'warehouses.view',
    columns: [
      { title: 'Ma kho', dataIndex: 'warehouse_code' },
      { title: 'Ten kho', dataIndex: 'warehouse_name' },
      { title: 'Dia chi', dataIndex: 'address' },
      { title: 'Quan ly', dataIndex: 'manager_name' },
      { title: 'Suc chua', dataIndex: 'capacity' },
      { title: 'Trang thai', dataIndex: 'status', type: 'status' },
    ],
    fields: [
      { name: 'warehouse_code', label: 'Ma kho', required: true },
      { name: 'warehouse_name', label: 'Ten kho', required: true },
      { name: 'address', label: 'Dia chi' },
      { name: 'manager_id', label: 'Nguoi phu trach', type: 'select', options: { endpoint: '/directory/users', labelField: 'full_name', valueField: 'id' } },
      { name: 'capacity', label: 'Suc chua', type: 'number' },
      { name: 'status', label: 'Trang thai', type: 'select', options: { static: [{ label: 'Active', value: 'active' }, { label: 'Inactive', value: 'inactive' }] } },
    ],
  },
  locations: {
    title: 'Vi tri kho',
    subtitle: 'Khu vuc, ke va o chua trong tung kho.',
    endpoint: '/locations',
    permission: 'locations.view',
    columns: [
      { title: 'Kho', dataIndex: 'warehouse_name' },
      { title: 'Zone', dataIndex: 'zone' },
      { title: 'Shelf', dataIndex: 'shelf' },
      { title: 'Bin', dataIndex: 'bin_code' },
      { title: 'Ghi chu', dataIndex: 'note' },
    ],
    fields: [
      { name: 'warehouse_id', label: 'Kho', type: 'select', required: true, options: { endpoint: '/warehouses', labelField: 'warehouse_name', valueField: 'id' } },
      { name: 'zone', label: 'Zone' },
      { name: 'shelf', label: 'Shelf' },
      { name: 'bin_code', label: 'Bin code', required: true },
      { name: 'note', label: 'Ghi chu', type: 'textarea' },
    ],
  },
  products: {
    title: 'Hang hoa',
    subtitle: 'Danh muc san pham va thong so ton kho.',
    endpoint: '/products',
    permission: 'products.view',
    columns: [
      { title: 'Ma hang', dataIndex: 'product_code' },
      { title: 'Ten hang', dataIndex: 'product_name' },
      { title: 'Nhom', dataIndex: 'category_name' },
      { title: 'Nha cung cap', dataIndex: 'supplier_name' },
      { title: 'Gia nhap', dataIndex: 'import_price', render: formatCurrency },
      { title: 'Gia ban', dataIndex: 'export_price', render: formatCurrency },
      { title: 'Ton tong', dataIndex: 'quantity_total' },
      { title: 'Trang thai', dataIndex: 'status', type: 'status' },
    ],
    fields: [
      { name: 'product_code', label: 'Ma hang', required: true },
      { name: 'product_name', label: 'Ten hang', required: true },
      { name: 'category_id', label: 'Nhom hang', type: 'select', options: { endpoint: '/categories', labelField: 'category_name', valueField: 'id' } },
      { name: 'supplier_id', label: 'Nha cung cap', type: 'select', options: { endpoint: '/suppliers', labelField: 'supplier_name', valueField: 'id' } },
      { name: 'unit', label: 'Don vi tinh', required: true },
      { name: 'import_price', label: 'Gia nhap', type: 'number', required: true },
      { name: 'export_price', label: 'Gia ban', type: 'number', required: true },
      { name: 'min_stock', label: 'Ton toi thieu', type: 'number' },
      { name: 'max_stock', label: 'Ton toi da', type: 'number' },
      { name: 'status', label: 'Trang thai', type: 'select', options: { static: [{ label: 'Active', value: 'active' }, { label: 'Inactive', value: 'inactive' }] } },
      { name: 'description', label: 'Mo ta', type: 'textarea' },
    ],
  },
  'bank-accounts': {
    title: 'Tai khoan ngan hang',
    subtitle: 'Thong tin doi soat thanh toan.',
    endpoint: '/bank-accounts',
    permission: 'bank_accounts.view',
    columns: [
      { title: 'Ngan hang', dataIndex: 'bank_name' },
      { title: 'So tai khoan', dataIndex: 'account_number' },
      { title: 'Chu tai khoan', dataIndex: 'account_holder' },
      { title: 'Chi nhanh', dataIndex: 'branch' },
      { title: 'Trang thai', dataIndex: 'status', type: 'status' },
    ],
    fields: [
      { name: 'bank_name', label: 'Ten ngan hang', required: true },
      { name: 'account_number', label: 'So tai khoan', required: true },
      { name: 'account_holder', label: 'Chu tai khoan', required: true },
      { name: 'branch', label: 'Chi nhanh' },
      { name: 'status', label: 'Trang thai', type: 'select', options: { static: [{ label: 'Active', value: 'active' }, { label: 'Inactive', value: 'inactive' }] } },
    ],
  },
  tasks: {
    title: 'Cong viec',
    subtitle: 'Phan cong va theo doi tien do.',
    endpoint: '/tasks',
    permission: 'tasks.view',
    columns: [
      { title: 'Tieu de', dataIndex: 'title' },
      { title: 'Lien quan', dataIndex: 'related_module' },
      { title: 'Nguoi giao', dataIndex: 'assigned_by_name' },
      { title: 'Nguoi nhan', dataIndex: 'assigned_to_name' },
      { title: 'Han xu ly', dataIndex: 'deadline', render: formatDateTime },
      { title: 'Trang thai', dataIndex: 'status', type: 'status' },
    ],
    fields: [
      { name: 'title', label: 'Tieu de', required: true },
      { name: 'description', label: 'Mo ta', type: 'textarea' },
      { name: 'assigned_to', label: 'Nguoi nhan', type: 'select', options: { endpoint: '/directory/users', labelField: 'full_name', valueField: 'id' } },
      { name: 'related_module', label: 'Phan he' },
      { name: 'deadline', label: 'Han xu ly', type: 'datetime' },
      { name: 'status', label: 'Trang thai', type: 'select', options: { static: [{ label: 'Pending', value: 'pending' }, { label: 'In Progress', value: 'in_progress' }, { label: 'Done', value: 'done' }] } },
    ],
  },
};
