const roleLabels = {
  admin: 'Quản trị viên',
  manager: 'Quản lý',
  staff: 'Nhân viên kho',
  accountant: 'Kế toán',
  shipper: 'Nhân viên giao hàng',
};

const statusOptions = [
  { label: 'Đang hoạt động', value: 'active' },
  { label: 'Ngừng hoạt động', value: 'inactive' },
];

export const resourceConfig = {
  users: {
    title: 'Tài khoản người dùng',
    subtitle: 'Quản lý đăng nhập, vai trò, trạng thái hoạt động và theo dõi yêu cầu đổi mật khẩu lần đầu hoặc sau khi reset.',
    eyebrow: 'Module 1-2 · Người dùng',
    endpoint: '/users',
    permission: 'users.view',
    managePermission: 'users.manage',
    serverSide: true,
    defaultPageSize: 10,
    defaultSort: { field: 'created_at', order: 'descend' },
    listTitle: 'Danh sách tài khoản',
    createLabel: 'Tạo tài khoản',
    editLabel: 'Chỉnh sửa tài khoản',
    searchPlaceholder: 'Tìm theo tên đăng nhập, họ tên, email hoặc mã nhân sự',
    emptyDescription: 'Chưa có tài khoản nào trong hệ thống.',
    toolbarHint: 'Danh sách dùng phân trang, lọc và sắp xếp ở phía server để xử lý tốt khi số lượng user tăng lớn.',
    drawerDescription: 'Nếu để trống mật khẩu khi tạo mới, hệ thống sẽ dùng mật khẩu mặc định và bắt buộc user đổi ở lần đăng nhập đầu tiên.',
    tips: [
      'Chỉ admin được quản lý tài khoản.',
      'Reset mật khẩu sẽ bật lại cờ bắt buộc đổi mật khẩu.',
      'Tài khoản có thể liên kết 1-1 với hồ sơ nhân sự.',
    ],
    listFilters: [
      {
        name: 'role_id',
        type: 'select',
        placeholder: 'Lọc theo vai trò',
        width: 220,
        options: {
          endpoint: '/roles',
          labelField: 'role_name',
          valueField: 'id',
          labelFormatter: (item) => `${roleLabels[item.role_name] || item.role_name} (${item.role_name})`,
        },
      },
      {
        name: 'has_employee',
        type: 'select',
        placeholder: 'Liên kết nhân sự',
        width: 220,
        options: {
          static: [
            { label: 'Đã liên kết nhân sự', value: 'true' },
            { label: 'Chưa liên kết nhân sự', value: 'false' },
          ],
        },
      },
    ],
    columns: [
      { title: 'Tên đăng nhập', dataIndex: 'username', sortable: true, sorterKey: 'username' },
      { title: 'Họ và tên', dataIndex: 'full_name', sortable: true, sorterKey: 'full_name' },
      { title: 'Email', dataIndex: 'email', sortable: true, sorterKey: 'email' },
      {
        title: 'Vai trò',
        dataIndex: 'role',
        render: (value) => roleLabels[value] || value || 'Chưa gán',
      },
      {
        title: 'Nhân sự liên kết',
        dataIndex: 'employee_code',
        render: (value) => value || 'Chưa liên kết',
      },
      {
        title: 'Đổi mật khẩu',
        dataIndex: 'must_change_password',
        render: (value) => (value ? 'Bắt buộc đổi' : 'Bình thường'),
      },
      { title: 'Trạng thái', dataIndex: 'status', type: 'status', sortable: true, sorterKey: 'status' },
    ],
    fields: [
      {
        name: 'username',
        label: 'Tên đăng nhập',
        required: true,
        placeholder: 'Ví dụ: nguyenvana',
        help: 'Nên dùng chuỗi ngắn gọn, dễ nhớ để nhân sự đăng nhập.',
        section: 'Thông tin tài khoản',
      },
      {
        name: 'password',
        label: 'Mật khẩu',
        type: 'password',
        placeholder: 'Để trống để dùng mật khẩu mặc định',
        help: 'Mật khẩu phải có ít nhất 8 ký tự, gồm chữ hoa, chữ thường, số và ký tự đặc biệt.',
        section: 'Thông tin tài khoản',
      },
      {
        name: 'full_name',
        label: 'Họ và tên',
        required: true,
        placeholder: 'Ví dụ: Nguyễn Văn A',
        section: 'Thông tin liên hệ',
      },
      {
        name: 'email',
        label: 'Email',
        required: true,
        placeholder: 'name@company.com',
        section: 'Thông tin liên hệ',
      },
      {
        name: 'phone',
        label: 'Số điện thoại',
        placeholder: 'Ví dụ: 0901234567',
        section: 'Thông tin liên hệ',
      },
      {
        name: 'role_id',
        label: 'Vai trò',
        type: 'select',
        required: true,
        placeholder: 'Chọn vai trò phù hợp',
        help: 'Vai trò quyết định phạm vi quyền mặc định của tài khoản. Có thể gõ tên vai trò mới rồi bấm thêm để lưu vào database.',
        options: {
          endpoint: '/roles',
          createEndpoint: '/roles',
          createPayloadKey: 'role_name',
          createLabel: 'Thêm vai trò mới',
          labelField: 'role_name',
          valueField: 'id',
          labelFormatter: (item) => `${roleLabels[item.role_name] || item.role_name} (${item.role_name})`,
        },
        section: 'Phân quyền và trạng thái',
      },
      {
        name: 'status',
        label: 'Trạng thái',
        type: 'select',
        initialValue: 'active',
        placeholder: 'Chọn trạng thái',
        options: { static: statusOptions },
        section: 'Phân quyền và trạng thái',
      },
    ],
  },
  employees: {
    title: 'Nhân sự',
    subtitle: 'Theo dõi hồ sơ nhân viên, phòng ban, chức vụ và liên kết 1-1 với tài khoản đăng nhập khi cần.',
    eyebrow: 'Module 2 · Nhân sự',
    endpoint: '/employees',
    permission: 'employees.view',
    managePermission: 'employees.manage',
    serverSide: true,
    defaultPageSize: 10,
    defaultSort: { field: 'created_at', order: 'descend' },
    listTitle: 'Danh sách nhân sự',
    createLabel: 'Tạo hồ sơ nhân sự',
    editLabel: 'Chỉnh sửa hồ sơ nhân sự',
    searchPlaceholder: 'Tìm theo mã nhân viên, họ tên, phòng ban, chức vụ hoặc tài khoản',
    emptyDescription: 'Chưa có hồ sơ nhân sự nào.',
    toolbarHint: 'Trang này cũng dùng lọc và sắp xếp ở phía server để chịu tải tốt với dữ liệu nhiều phòng ban.',
    drawerDescription: 'Nếu để trống mã nhân viên khi tạo mới, hệ thống sẽ tự sinh theo viết tắt phòng ban.',
    tips: [
      'Manager được phép quản lý nhân sự.',
      'Một tài khoản chỉ gắn tối đa một hồ sơ nhân sự.',
      'Có thể để trống tài khoản liên kết nếu nhân sự chưa cần đăng nhập.',
    ],
    listFilters: [
      {
        name: 'has_user',
        type: 'select',
        placeholder: 'Liên kết tài khoản',
        width: 220,
        options: {
          static: [
            { label: 'Đã liên kết tài khoản', value: 'true' },
            { label: 'Chưa liên kết tài khoản', value: 'false' },
          ],
        },
      },
    ],
    columns: [
      { title: 'Mã nhân viên', dataIndex: 'employee_code', sortable: true, sorterKey: 'employee_code' },
      { title: 'Họ và tên', dataIndex: 'full_name', sortable: true, sorterKey: 'full_name' },
      {
        title: 'Phòng ban',
        dataIndex: 'department',
        sortable: true,
        sorterKey: 'department',
        render: (value) => value || 'Chưa cập nhật',
      },
      {
        title: 'Chức vụ',
        dataIndex: 'position',
        sortable: true,
        sorterKey: 'position',
        render: (value) => value || 'Chưa cập nhật',
      },
      { title: 'Tài khoản', dataIndex: 'username', render: (value) => value || 'Chưa liên kết' },
      { title: 'Vai trò', dataIndex: 'role', render: (value) => roleLabels[value] || value || 'Chưa gán' },
      { title: 'Trạng thái', dataIndex: 'status', type: 'status', sortable: true, sorterKey: 'status' },
    ],
    fields: [
      {
        name: 'employee_code',
        label: 'Mã nhân viên',
        placeholder: 'Để trống để hệ thống tự sinh, ví dụ VHK-001',
        help: 'Hệ thống sẽ dùng viết tắt từ phòng ban để tạo mã nếu bạn không nhập tay.',
        section: 'Thông tin hồ sơ',
      },
      {
        name: 'full_name',
        label: 'Họ và tên',
        required: true,
        placeholder: 'Ví dụ: Trần Thị B',
        section: 'Thông tin hồ sơ',
      },
      {
        name: 'department',
        label: 'Phòng ban',
        placeholder: 'Ví dụ: Vận hành kho',
        section: 'Thông tin công việc',
      },
      {
        name: 'position',
        label: 'Chức vụ',
        placeholder: 'Ví dụ: Thủ kho',
        section: 'Thông tin công việc',
      },
      {
        name: 'user_id',
        label: 'Tài khoản liên kết',
        type: 'select',
        placeholder: 'Chọn tài khoản nếu nhân sự cần đăng nhập',
        help: 'Có thể để trống nếu đây chỉ là hồ sơ quản lý nội bộ.',
        options: {
          endpoint: '/directory/users',
          labelField: 'full_name',
          valueField: 'id',
          labelFormatter: (item) => `${item.full_name} (${item.username})`,
        },
        section: 'Liên hệ và truy cập',
        span: 24,
      },
      {
        name: 'phone',
        label: 'Số điện thoại',
        placeholder: 'Ví dụ: 0901234567',
        section: 'Liên hệ và truy cập',
      },
      {
        name: 'email',
        label: 'Email',
        placeholder: 'name@company.com',
        section: 'Liên hệ và truy cập',
      },
      {
        name: 'status',
        label: 'Trạng thái',
        type: 'select',
        initialValue: 'active',
        placeholder: 'Chọn trạng thái',
        options: { static: statusOptions },
        section: 'Liên hệ và truy cập',
      },
    ],
  },
  categories: {
    title: 'Nhóm hàng',
    subtitle: 'Quản lý các nhóm hàng dùng chung cho toàn hệ thống để chuẩn hóa dữ liệu sản phẩm ở các module sau.',
    eyebrow: 'Module 3 · Danh mục nền',
    endpoint: '/categories',
    permission: 'categories.view',
    managePermission: 'categories.manage',
    serverSide: true,
    defaultPageSize: 10,
    defaultSort: { field: 'category_name', order: 'ascend' },
    listTitle: 'Danh sách nhóm hàng',
    createLabel: 'Thêm nhóm hàng',
    editLabel: 'Chỉnh sửa nhóm hàng',
    searchPlaceholder: 'Tìm theo tên nhóm hàng hoặc mô tả',
    emptyDescription: 'Chưa có nhóm hàng nào.',
    toolbarHint: 'Dùng nhóm hàng rõ ràng sẽ giúp quản lý sản phẩm, báo cáo và tìm kiếm nhanh hơn ở các module sau.',
    drawerDescription: 'Nhóm hàng hiện giữ ở mức tối giản gồm tên và mô tả ngắn để dễ nhập liệu, dễ demo và dễ mở rộng sau này.',
    tips: [
      'Tên nhóm hàng phải là duy nhất.',
      'Manager được quản lý nhóm hàng.',
      'Category chưa có trạng thái trong Module 3.',
    ],
    columns: [
      { title: 'Tên nhóm hàng', dataIndex: 'category_name', sortable: true, sorterKey: 'category_name' },
      {
        title: 'Mô tả',
        dataIndex: 'description',
        render: (value) => value || 'Chưa có mô tả',
      },
      { title: 'Cập nhật gần nhất', dataIndex: 'updated_at', sortable: true, sorterKey: 'updated_at' },
    ],
    fields: [
      {
        name: 'category_name',
        label: 'Tên nhóm hàng',
        required: true,
        placeholder: 'Ví dụ: Điện tử, Văn phòng phẩm',
        help: 'Tên nhóm hàng phải duy nhất để tránh trùng lặp khi tạo sản phẩm.',
        section: 'Thông tin nhóm hàng',
        span: 24,
      },
      {
        name: 'description',
        label: 'Mô tả',
        type: 'textarea',
        placeholder: 'Mô tả ngắn về phạm vi của nhóm hàng này',
        section: 'Thông tin nhóm hàng',
        span: 24,
      },
    ],
  },
  suppliers: {
    title: 'Nhà cung cấp',
    subtitle: 'Quản lý đối tác cung ứng để chuẩn bị cho nghiệp vụ nhập hàng, đối chiếu chứng từ và mở rộng quản lý công nợ sau này.',
    eyebrow: 'Module 3 · Danh mục nền',
    endpoint: '/suppliers',
    permission: 'suppliers.view',
    managePermission: 'suppliers.manage',
    serverSide: true,
    defaultPageSize: 10,
    defaultSort: { field: 'supplier_code', order: 'ascend' },
    listTitle: 'Danh sách nhà cung cấp',
    createLabel: 'Thêm nhà cung cấp',
    editLabel: 'Chỉnh sửa nhà cung cấp',
    searchPlaceholder: 'Tìm theo mã, tên, email hoặc số điện thoại',
    emptyDescription: 'Chưa có nhà cung cấp nào.',
    toolbarHint: 'Có thể lọc nhanh theo trạng thái hoạt động để tìm đúng đối tác đang dùng.',
    drawerDescription: 'Mã nhà cung cấp đang nhập tay để dễ kiểm soát khi demo; module sau có thể bổ sung sinh mã tự động nếu cần.',
    tips: [
      'Mã nhà cung cấp phải là duy nhất.',
      'Manager được quản lý nhà cung cấp.',
      'Có thể dùng trạng thái để tạm ngừng sử dụng mà chưa cần xóa ngay.',
    ],
    columns: [
      { title: 'Mã nhà cung cấp', dataIndex: 'supplier_code', sortable: true, sorterKey: 'supplier_code' },
      { title: 'Tên nhà cung cấp', dataIndex: 'supplier_name', sortable: true, sorterKey: 'supplier_name' },
      { title: 'Email', dataIndex: 'email', sortable: true, sorterKey: 'email', render: (value) => value || 'Chưa cập nhật' },
      { title: 'Số điện thoại', dataIndex: 'phone', render: (value) => value || 'Chưa cập nhật' },
      { title: 'Trạng thái', dataIndex: 'status', type: 'status', sortable: true, sorterKey: 'status' },
    ],
    fields: [
      {
        name: 'supplier_code',
        label: 'Mã nhà cung cấp',
        required: true,
        placeholder: 'Ví dụ: SUP001',
        help: 'Mã được dùng để tìm kiếm nhanh và liên kết chứng từ về sau.',
        section: 'Thông tin định danh',
      },
      {
        name: 'supplier_name',
        label: 'Tên nhà cung cấp',
        required: true,
        placeholder: 'Ví dụ: Công ty Thiết bị Sao Mai',
        section: 'Thông tin định danh',
      },
      {
        name: 'email',
        label: 'Email',
        placeholder: 'contact@supplier.com',
        section: 'Thông tin liên hệ',
      },
      {
        name: 'phone',
        label: 'Số điện thoại',
        placeholder: 'Ví dụ: 02812345678',
        section: 'Thông tin liên hệ',
      },
      {
        name: 'address',
        label: 'Địa chỉ',
        type: 'textarea',
        placeholder: 'Địa chỉ giao dịch hoặc kho lấy hàng',
        section: 'Thông tin liên hệ',
        span: 24,
      },
      {
        name: 'status',
        label: 'Trạng thái',
        type: 'select',
        initialValue: 'active',
        placeholder: 'Chọn trạng thái',
        options: { static: statusOptions },
        section: 'Trạng thái sử dụng',
        span: 24,
      },
    ],
  },
  customers: {
    title: 'Khách hàng',
    subtitle: 'Quản lý khách hàng mua hàng để chuẩn bị cho luồng xuất kho, vận chuyển, hóa đơn và thanh toán ở các module tiếp theo.',
    eyebrow: 'Module 3 · Danh mục nền',
    endpoint: '/customers',
    permission: 'customers.view',
    managePermission: 'customers.manage',
    serverSide: true,
    defaultPageSize: 10,
    defaultSort: { field: 'customer_code', order: 'ascend' },
    listTitle: 'Danh sách khách hàng',
    createLabel: 'Thêm khách hàng',
    editLabel: 'Chỉnh sửa khách hàng',
    searchPlaceholder: 'Tìm theo mã, tên, email hoặc số điện thoại',
    emptyDescription: 'Chưa có khách hàng nào.',
    toolbarHint: 'Kế toán và quản lý đều có thể dùng danh mục này để chuẩn bị cho nghiệp vụ hóa đơn và thanh toán.',
    drawerDescription: 'Mã khách hàng đang nhập tay để đồng bộ với cách doanh nghiệp thường đặt mã trong giai đoạn đầu triển khai.',
    tips: [
      'Mã khách hàng phải là duy nhất.',
      'Manager và kế toán đều có thể quản lý khách hàng.',
      'Lọc theo trạng thái giúp rà soát danh sách khách đang hoạt động nhanh hơn.',
    ],
    columns: [
      { title: 'Mã khách hàng', dataIndex: 'customer_code', sortable: true, sorterKey: 'customer_code' },
      { title: 'Tên khách hàng', dataIndex: 'customer_name', sortable: true, sorterKey: 'customer_name' },
      { title: 'Email', dataIndex: 'email', sortable: true, sorterKey: 'email', render: (value) => value || 'Chưa cập nhật' },
      { title: 'Số điện thoại', dataIndex: 'phone', render: (value) => value || 'Chưa cập nhật' },
      { title: 'Trạng thái', dataIndex: 'status', type: 'status', sortable: true, sorterKey: 'status' },
    ],
    fields: [
      {
        name: 'customer_code',
        label: 'Mã khách hàng',
        required: true,
        placeholder: 'Ví dụ: CUS001',
        help: 'Mã khách hàng hỗ trợ truy vết nhanh khi lập phiếu xuất và hóa đơn.',
        section: 'Thông tin định danh',
      },
      {
        name: 'customer_name',
        label: 'Tên khách hàng',
        required: true,
        placeholder: 'Ví dụ: Công ty Thương mại Bình Minh',
        section: 'Thông tin định danh',
      },
      {
        name: 'email',
        label: 'Email',
        placeholder: 'contact@customer.com',
        section: 'Thông tin liên hệ',
      },
      {
        name: 'phone',
        label: 'Số điện thoại',
        placeholder: 'Ví dụ: 0905123456',
        section: 'Thông tin liên hệ',
      },
      {
        name: 'address',
        label: 'Địa chỉ',
        type: 'textarea',
        placeholder: 'Địa chỉ giao hàng hoặc trụ sở khách hàng',
        section: 'Thông tin liên hệ',
        span: 24,
      },
      {
        name: 'status',
        label: 'Trạng thái',
        type: 'select',
        initialValue: 'active',
        placeholder: 'Chọn trạng thái',
        options: { static: statusOptions },
        section: 'Trạng thái sử dụng',
        span: 24,
      },
    ],
  },
  bank_accounts: {
    title: 'Tài khoản ngân hàng',
    subtitle: 'Quản lý tài khoản ngân hàng doanh nghiệp dùng để nhận thanh toán và phục vụ đối soát ở các module kế tiếp.',
    eyebrow: 'Module 3 · Danh mục nền',
    endpoint: '/bank-accounts',
    permission: 'bank_accounts.view',
    managePermission: 'bank_accounts.manage',
    serverSide: true,
    defaultPageSize: 10,
    defaultSort: { field: 'account_number', order: 'ascend' },
    listTitle: 'Danh sách tài khoản ngân hàng',
    createLabel: 'Thêm tài khoản ngân hàng',
    editLabel: 'Chỉnh sửa tài khoản ngân hàng',
    searchPlaceholder: 'Tìm theo ngân hàng, số tài khoản, chủ tài khoản hoặc chi nhánh',
    emptyDescription: 'Chưa có tài khoản ngân hàng nào.',
    toolbarHint: 'Chỉ admin và kế toán được quản lý danh mục này để đảm bảo an toàn nghiệp vụ thanh toán.',
    drawerDescription: 'Module 3 cho phép hard delete khi chưa có tham chiếu nghiệp vụ; các module sau sẽ tự chặn xóa khi đã phát sinh dữ liệu liên quan.',
    tips: [
      'Số tài khoản phải là duy nhất.',
      'Kế toán được quản lý tài khoản ngân hàng.',
      'Có thể đặt trạng thái ngừng hoạt động để tạm khóa sử dụng.',
    ],
    columns: [
      { title: 'Ngân hàng', dataIndex: 'bank_name', sortable: true, sorterKey: 'bank_name' },
      { title: 'Số tài khoản', dataIndex: 'account_number', sortable: true, sorterKey: 'account_number' },
      { title: 'Chủ tài khoản', dataIndex: 'account_holder', sortable: true, sorterKey: 'account_holder' },
      { title: 'Chi nhánh', dataIndex: 'branch', render: (value) => value || 'Chưa cập nhật' },
      { title: 'Trạng thái', dataIndex: 'status', type: 'status', sortable: true, sorterKey: 'status' },
    ],
    fields: [
      {
        name: 'bank_name',
        label: 'Tên ngân hàng',
        required: true,
        placeholder: 'Ví dụ: Vietcombank',
        section: 'Thông tin tài khoản',
      },
      {
        name: 'account_number',
        label: 'Số tài khoản',
        required: true,
        placeholder: 'Ví dụ: 0123456789',
        help: 'Số tài khoản được trim trước khi lưu và phải là duy nhất trong hệ thống.',
        section: 'Thông tin tài khoản',
      },
      {
        name: 'account_holder',
        label: 'Chủ tài khoản',
        required: true,
        placeholder: 'Ví dụ: Công ty ABC',
        section: 'Thông tin tài khoản',
      },
      {
        name: 'branch',
        label: 'Chi nhánh',
        placeholder: 'Ví dụ: Chi nhánh Quận 1',
        section: 'Thông tin bổ sung',
      },
      {
        name: 'status',
        label: 'Trạng thái',
        type: 'select',
        initialValue: 'active',
        placeholder: 'Chọn trạng thái',
        options: { static: statusOptions },
        section: 'Thông tin bổ sung',
      },
    ],
  },
  products: {
    title: 'Sản phẩm',
    subtitle: 'Quản lý danh mục sản phẩm với mã hàng, nhóm hàng, mức tồn tối thiểu và trạng thái sử dụng để sẵn sàng cho các bước nhập xuất kho phía sau.',
    eyebrow: 'Module 4 · Sản phẩm',
    endpoint: '/products',
    permission: 'products.view',
    managePermission: 'products.manage',
    serverSide: true,
    defaultPageSize: 10,
    defaultSort: { field: 'product_code', order: 'ascend' },
    listTitle: 'Danh sách sản phẩm',
    createLabel: 'Thêm sản phẩm',
    editLabel: 'Chỉnh sửa sản phẩm',
    searchPlaceholder: 'Tìm theo mã sản phẩm, tên sản phẩm, mô tả hoặc nhóm hàng',
    emptyDescription: 'Chưa có sản phẩm nào trong hệ thống.',
    toolbarHint: 'Sản phẩm là dữ liệu gốc cho kho và tồn kho, nên mã hàng và nhóm hàng cần được chuẩn hóa ngay từ đầu.',
    drawerDescription: 'Module 4 chỉ cho chỉnh thông tin master của sản phẩm. Số lượng tồn hiện tại được đọc từ inventory flow và chưa được sửa trực tiếp ở màn hình này.',
    tips: [
      'Mã sản phẩm phải là duy nhất.',
      'Quản lý và quản trị viên được tạo, sửa, xóa sản phẩm.',
      'Nhân viên kho chỉ xem danh sách để phục vụ kiểm kê và tra cứu.',
      'Số lượng tồn hiện tại là dữ liệu chỉ đọc trong Module 4.',
    ],
    columns: [
      { title: 'Mã sản phẩm', dataIndex: 'product_code', sortable: true, sorterKey: 'product_code' },
      { title: 'Tên sản phẩm', dataIndex: 'product_name', sortable: true, sorterKey: 'product_name' },
      {
        title: 'Nhóm hàng',
        dataIndex: 'category_name',
        render: (value) => value || 'Chưa gán nhóm hàng',
      },
      {
        title: 'Tồn hiện tại',
        dataIndex: 'quantity_total',
        sortable: true,
        sorterKey: 'quantity_total',
      },
      {
        title: 'Tồn tối thiểu',
        dataIndex: 'min_stock',
        sortable: true,
        sorterKey: 'min_stock',
      },
      {
        title: 'Cảnh báo tồn',
        dataIndex: 'is_below_min_stock',
        render: (value) => (value ? 'Dưới ngưỡng' : 'An toàn'),
      },
      { title: 'Trạng thái', dataIndex: 'status', type: 'status', sortable: true, sorterKey: 'status' },
    ],
    fields: [
      {
        name: 'product_code',
        label: 'Mã sản phẩm',
        required: true,
        placeholder: 'Ví dụ: PRD001',
        help: 'Mã sản phẩm dùng để truy vết xuyên suốt các module kho, vận chuyển và báo cáo.',
        section: 'Thông tin định danh',
      },
      {
        name: 'product_name',
        label: 'Tên sản phẩm',
        required: true,
        placeholder: 'Ví dụ: Máy quét mã vạch',
        section: 'Thông tin định danh',
      },
      {
        name: 'category_id',
        label: 'Nhóm hàng',
        type: 'select',
        required: true,
        placeholder: 'Chọn nhóm hàng phù hợp',
        options: {
          endpoint: '/categories',
          labelField: 'category_name',
          valueField: 'id',
        },
        section: 'Thông tin phân loại',
      },
      {
        name: 'min_stock',
        label: 'Tồn tối thiểu',
        type: 'number',
        placeholder: 'Ví dụ: 10',
        help: 'Mức tồn tối thiểu để phục vụ cảnh báo tồn thấp ở bước demo sau.',
        section: 'Thông tin phân loại',
      },
      {
        name: 'status',
        label: 'Trạng thái',
        type: 'select',
        initialValue: 'active',
        placeholder: 'Chọn trạng thái',
        options: { static: statusOptions },
        section: 'Thông tin bổ sung',
      },
      {
        name: 'description',
        label: 'Mô tả',
        type: 'textarea',
        placeholder: 'Mô tả ngắn về sản phẩm, công dụng hoặc ghi chú nhận diện',
        section: 'Thông tin bổ sung',
        span: 24,
      },
    ],
  },
};
