const roleLabels = {
  admin: 'Quản trị viên',
  manager: 'Quản lý',
  staff: 'Nhân viên kho',
  accountant: 'Kế toán',
  shipper: 'Nhân viên giao hàng',
};

export const resourceConfig = {
  users: {
    title: 'Tài khoản người dùng',
    subtitle: 'Quản lý đăng nhập, vai trò, trạng thái hoạt động và theo dõi yêu cầu đổi mật khẩu lần đầu hoặc sau khi reset.',
    eyebrow: 'Module 1-2 · Người dùng',
    endpoint: '/users',
    permission: 'users.view',
    managePermission: 'users.manage',
    serverSide: true,
    defaultPageSize: 10,
    defaultSort: { field: 'created_at', order: 'descend' },
    listTitle: 'Danh sách tài khoản',
    createLabel: 'Tạo tài khoản',
    editLabel: 'Chỉnh sửa tài khoản',
    searchPlaceholder: 'Tìm theo tên đăng nhập, họ tên, email hoặc mã nhân sự',
    emptyDescription: 'Chưa có tài khoản nào trong hệ thống.',
    toolbarHint: 'Danh sách dùng phân trang, lọc và sắp xếp ở phía server để xử lý tốt khi số lượng user tăng lớn.',
    drawerDescription: 'Nếu để trống mật khẩu khi tạo mới, hệ thống sẽ dùng mật khẩu mặc định và bắt buộc user đổi ở lần đăng nhập đầu tiên.',
    tips: [
      'Chỉ admin được quản lý tài khoản',
      'Reset mật khẩu sẽ bật lại cờ bắt buộc đổi mật khẩu',
      'Tài khoản có thể liên kết 1-1 với hồ sơ nhân sự',
    ],
    listFilters: [
      {
        name: 'role_id',
        type: 'select',
        placeholder: 'Lọc theo vai trò',
        width: 220,
        options: {
          endpoint: '/roles',
          labelField: 'role_name',
          valueField: 'id',
          labelFormatter: (item) => `${roleLabels[item.role_name] || item.role_name} (${item.role_name})`,
        },
      },
      {
        name: 'has_employee',
        type: 'select',
        placeholder: 'Liên kết nhân sự',
        width: 220,
        options: {
          static: [
            { label: 'Đã liên kết nhân sự', value: 'true' },
            { label: 'Chưa liên kết nhân sự', value: 'false' },
          ],
        },
      },
    ],
    columns: [
      { title: 'Tên đăng nhập', dataIndex: 'username', sortable: true, sorterKey: 'username' },
      { title: 'Họ và tên', dataIndex: 'full_name', sortable: true, sorterKey: 'full_name' },
      { title: 'Email', dataIndex: 'email', sortable: true, sorterKey: 'email' },
      {
        title: 'Vai trò',
        dataIndex: 'role',
        render: (value) => roleLabels[value] || value || 'Chưa gán',
      },
      {
        title: 'Nhân sự liên kết',
        dataIndex: 'employee_code',
        render: (value) => value || 'Chưa liên kết',
      },
      {
        title: 'Đổi mật khẩu',
        dataIndex: 'must_change_password',
        render: (value) => (value ? 'Bắt buộc đổi' : 'Bình thường'),
      },
      { title: 'Trạng thái', dataIndex: 'status', type: 'status', sortable: true, sorterKey: 'status' },
    ],
    fields: [
      {
        name: 'username',
        label: 'Tên đăng nhập',
        required: true,
        placeholder: 'Ví dụ: nguyenvana',
        help: 'Nên dùng chuỗi ngắn gọn, dễ nhớ để nhân sự đăng nhập.',
        section: 'Thông tin tài khoản',
      },
      {
        name: 'password',
        label: 'Mật khẩu',
        type: 'password',
        placeholder: 'Để trống để dùng mật khẩu mặc định',
        help: 'Mật khẩu phải có ít nhất 8 ký tự, gồm chữ hoa, chữ thường, số và ký tự đặc biệt.',
        section: 'Thông tin tài khoản',
      },
      {
        name: 'full_name',
        label: 'Họ và tên',
        required: true,
        placeholder: 'Ví dụ: Nguyễn Văn A',
        section: 'Thông tin liên hệ',
      },
      {
        name: 'email',
        label: 'Email',
        required: true,
        placeholder: 'name@company.com',
        section: 'Thông tin liên hệ',
      },
      {
        name: 'phone',
        label: 'Số điện thoại',
        placeholder: 'Ví dụ: 0901234567',
        section: 'Thông tin liên hệ',
      },
      {
        name: 'role_id',
        label: 'Vai trò',
        type: 'select',
        required: true,
        placeholder: 'Chọn vai trò phù hợp',
        help: 'Vai trò quyết định phạm vi quyền mặc định của tài khoản. Có thể gõ tên vai trò mới rồi bấm thêm để lưu vào database.',
        options: {
          endpoint: '/roles',
          createEndpoint: '/roles',
          createPayloadKey: 'role_name',
          createLabel: 'Thêm vai trò mới',
          labelField: 'role_name',
          valueField: 'id',
          labelFormatter: (item) => `${roleLabels[item.role_name] || item.role_name} (${item.role_name})`,
        },
        section: 'Phân quyền và trạng thái',
      },
      {
        name: 'status',
        label: 'Trạng thái',
        type: 'select',
        initialValue: 'active',
        placeholder: 'Chọn trạng thái',
        options: {
          static: [
            { label: 'Đang hoạt động', value: 'active' },
            { label: 'Ngừng hoạt động', value: 'inactive' },
          ],
        },
        section: 'Phân quyền và trạng thái',
      },
    ],
  },
  employees: {
    title: 'Nhân sự',
    subtitle: 'Theo dõi hồ sơ nhân viên, phòng ban, chức vụ và liên kết 1-1 với tài khoản đăng nhập khi cần.',
    eyebrow: 'Module 2 · Nhân sự',
    endpoint: '/employees',
    permission: 'employees.view',
    managePermission: 'employees.manage',
    serverSide: true,
    defaultPageSize: 10,
    defaultSort: { field: 'created_at', order: 'descend' },
    listTitle: 'Danh sách nhân sự',
    createLabel: 'Tạo hồ sơ nhân sự',
    editLabel: 'Chỉnh sửa hồ sơ nhân sự',
    searchPlaceholder: 'Tìm theo mã nhân viên, họ tên, phòng ban, chức vụ hoặc tài khoản',
    emptyDescription: 'Chưa có hồ sơ nhân sự nào.',
    toolbarHint: 'Trang này cũng dùng lọc và sắp xếp ở phía server để chịu tải tốt với dữ liệu nhiều phòng ban.',
    drawerDescription: 'Nếu để trống mã nhân viên khi tạo mới, hệ thống sẽ tự sinh theo viết tắt phòng ban.',
    tips: [
      'Manager được phép quản lý nhân sự',
      'Một tài khoản chỉ gắn tối đa một hồ sơ nhân sự',
      'Có thể để trống tài khoản liên kết nếu nhân sự chưa cần đăng nhập',
    ],
    listFilters: [
      {
        name: 'has_user',
        type: 'select',
        placeholder: 'Liên kết tài khoản',
        width: 220,
        options: {
          static: [
            { label: 'Đã liên kết tài khoản', value: 'true' },
            { label: 'Chưa liên kết tài khoản', value: 'false' },
          ],
        },
      },
    ],
    columns: [
      { title: 'Mã nhân viên', dataIndex: 'employee_code', sortable: true, sorterKey: 'employee_code' },
      { title: 'Họ và tên', dataIndex: 'full_name', sortable: true, sorterKey: 'full_name' },
      {
        title: 'Phòng ban',
        dataIndex: 'department',
        sortable: true,
        sorterKey: 'department',
        render: (value) => value || 'Chưa cập nhật',
      },
      {
        title: 'Chức vụ',
        dataIndex: 'position',
        sortable: true,
        sorterKey: 'position',
        render: (value) => value || 'Chưa cập nhật',
      },
      { title: 'Tài khoản', dataIndex: 'username', render: (value) => value || 'Chưa liên kết' },
      { title: 'Vai trò', dataIndex: 'role', render: (value) => roleLabels[value] || value || 'Chưa gán' },
      { title: 'Trạng thái', dataIndex: 'status', type: 'status', sortable: true, sorterKey: 'status' },
    ],
    fields: [
      {
        name: 'employee_code',
        label: 'Mã nhân viên',
        placeholder: 'Để trống để hệ thống tự sinh, ví dụ VHK-001',
        help: 'Hệ thống sẽ dùng viết tắt từ phòng ban để tạo mã nếu bạn không nhập tay.',
        section: 'Thông tin hồ sơ',
      },
      {
        name: 'full_name',
        label: 'Họ và tên',
        required: true,
        placeholder: 'Ví dụ: Trần Thị B',
        section: 'Thông tin hồ sơ',
      },
      {
        name: 'department',
        label: 'Phòng ban',
        placeholder: 'Ví dụ: Vận hành kho',
        section: 'Thông tin công việc',
      },
      {
        name: 'position',
        label: 'Chức vụ',
        placeholder: 'Ví dụ: Thủ kho',
        section: 'Thông tin công việc',
      },
      {
        name: 'user_id',
        label: 'Tài khoản liên kết',
        type: 'select',
        placeholder: 'Chọn tài khoản nếu nhân sự cần đăng nhập',
        help: 'Có thể để trống nếu đây chỉ là hồ sơ quản lý nội bộ.',
        options: {
          endpoint: '/directory/users',
          labelField: 'full_name',
          valueField: 'id',
          labelFormatter: (item) => `${item.full_name} (${item.username})`,
        },
        section: 'Liên hệ và truy cập',
        span: 24,
      },
      {
        name: 'phone',
        label: 'Số điện thoại',
        placeholder: 'Ví dụ: 0901234567',
        section: 'Liên hệ và truy cập',
      },
      {
        name: 'email',
        label: 'Email',
        placeholder: 'name@company.com',
        section: 'Liên hệ và truy cập',
      },
      {
        name: 'status',
        label: 'Trạng thái',
        type: 'select',
        initialValue: 'active',
        placeholder: 'Chọn trạng thái',
        options: {
          static: [
            { label: 'Đang hoạt động', value: 'active' },
            { label: 'Ngừng hoạt động', value: 'inactive' },
          ],
        },
        section: 'Liên hệ và truy cập',
      },
    ],
  },
};
