RESOURCE_PERMISSIONS = {
    "audit_logs.view",
    "bank_accounts.manage",
    "bank_accounts.view",
    "categories.manage",
    "categories.view",
    "chat.view",
    "customers.manage",
    "customers.view",
    "dashboard.view",
    "delegations.manage",
    "employees.manage",
    "employees.view",
    "export_receipts.manage",
    "export_receipts.view",
    "import_receipts.manage",
    "import_receipts.view",
    "invoices.manage",
    "invoices.view",
    "inventory.manage",
    "inventory.view",
    "locations.manage",
    "locations.view",
    "notifications.manage",
    "notifications.view",
    "products.manage",
    "products.view",
    "reports.view",
    "roles.view",
    "shipments.manage",
    "shipments.view",
    "stock_transfers.manage",
    "stock_transfers.view",
    "suppliers.manage",
    "suppliers.view",
    "tasks.manage",
    "tasks.view",
    "users.manage",
    "users.view",
    "warehouses.manage",
    "warehouses.view",
}

ROLE_DELEGATION_ALLOWED_TARGETS = {
    "admin": ["manager", "staff", "accountant", "shipper"],
    "manager": ["staff", "shipper"],
    "accountant": [],
    "staff": [],
    "shipper": [],
}

ROLE_PERMISSION_MAP = {
    "admin": [
        "audit_logs.view",
        "bank_accounts.manage",
        "bank_accounts.view",
        "categories.manage",
        "categories.view",
        "chat.view",
        "customers.manage",
        "customers.view",
        "dashboard.view",
        "delegations.manage",
        "employees.manage",
        "employees.view",
        "export_receipts.manage",
        "export_receipts.view",
        "import_receipts.manage",
        "import_receipts.view",
        "invoices.manage",
        "invoices.view",
        "inventory.manage",
        "inventory.view",
        "locations.manage",
        "locations.view",
        "notifications.manage",
        "notifications.view",
        "products.manage",
        "products.view",
        "reports.view",
        "roles.view",
        "shipments.manage",
        "shipments.view",
        "stock_transfers.manage",
        "stock_transfers.view",
        "suppliers.manage",
        "suppliers.view",
        "tasks.manage",
        "tasks.view",
        "users.manage",
        "users.view",
        "warehouses.manage",
        "warehouses.view",
    ],
    "manager": [
        "audit_logs.view",
        "categories.manage",
        "categories.view",
        "chat.view",
        "customers.manage",
        "customers.view",
        "dashboard.view",
        "delegations.manage",
        "employees.manage",
        "employees.view",
        "export_receipts.manage",
        "export_receipts.view",
        "import_receipts.manage",
        "import_receipts.view",
        "invoices.manage",
        "invoices.view",
        "inventory.manage",
        "inventory.view",
        "locations.manage",
        "locations.view",
        "notifications.manage",
        "notifications.view",
        "products.manage",
        "products.view",
        "reports.view",
        "shipments.manage",
        "shipments.view",
        "stock_transfers.manage",
        "stock_transfers.view",
        "suppliers.manage",
        "suppliers.view",
        "tasks.manage",
        "tasks.view",
        "warehouses.manage",
        "warehouses.view",
    ],
    "staff": [
        "chat.view",
        "dashboard.view",
        "export_receipts.manage",
        "export_receipts.view",
        "import_receipts.manage",
        "import_receipts.view",
        "inventory.manage",
        "inventory.view",
        "locations.view",
        "notifications.view",
        "products.view",
        "shipments.manage",
        "shipments.view",
        "stock_transfers.manage",
        "stock_transfers.view",
        "tasks.view",
        "warehouses.view",
    ],
    "accountant": [
        "bank_accounts.manage",
        "bank_accounts.view",
        "chat.view",
        "customers.manage",
        "customers.view",
        "dashboard.view",
        "invoices.manage",
        "invoices.view",
        "notifications.view",
        "reports.view",
        "tasks.view",
    ],
    "shipper": [
        "chat.view",
        "dashboard.view",
        "notifications.view",
        "shipments.manage",
        "shipments.view",
        "tasks.view",
    ],
}

DEFAULT_ROLE_PASSWORDS = {
    "admin": "Admin@123",
    "manager": "Manager@123",
    "staff": "Staff@123",
    "accountant": "Accountant@123",
    "shipper": "Shipper@123",
}
